#!/usr/bin/env python3
"""
Generate h8532.pspec: a Ghidra processor spec for the Hitachi H8/532 in
mode 3 (maximum mode, no on-chip ROM), used with the OZVR4 H8/500 SLEIGH
module's h8539f.sla.  Register addresses and vectors from
notes/reference/h8532-registers.md.

    python3 gen_pspec.py MODULE_LANGUAGES_DIR      # writes h8532.pspec here
"""
import os
import sys

REGS = {0xFF80: "P1DDR", 0xFF81: "P2DDR", 0xFF82: "P1DR", 0xFF83: "P2DR",
        0xFF84: "P3DDR", 0xFF85: "P4DDR", 0xFF86: "P3DR", 0xFF87: "P4DR",
        0xFF88: "P5DDR", 0xFF89: "P6DDR", 0xFF8A: "P5DR", 0xFF8B: "P6DR",
        0xFF8C: "P7DDR", 0xFF8E: "P7DR", 0xFF8F: "P8DR",
        0xFFD0: "TMR_TCR", 0xFFD1: "TMR_TCSR", 0xFFD2: "TMR_TCORA",
        0xFFD3: "TMR_TCORB", 0xFFD4: "TMR_TCNT",
        0xFFD8: "SMR", 0xFFD9: "BRR", 0xFFDA: "SCR", 0xFFDB: "TDR",
        0xFFDC: "SSR", 0xFFDD: "RDR",
        0xFFE0: "ADDRA", 0xFFE2: "ADDRB", 0xFFE4: "ADDRC", 0xFFE6: "ADDRD",
        0xFFE8: "ADCSR", 0xFFEC: "WDT_TCSR", 0xFFED: "WDT_TCNT",
        0xFFF0: "IPRA", 0xFFF1: "IPRB", 0xFFF2: "IPRC", 0xFFF3: "IPRD",
        0xFFF4: "DTEA", 0xFFF5: "DTEB", 0xFFF6: "DTEC", 0xFFF7: "DTED",
        0xFFF8: "WCR", 0xFFF9: "RAMCR", 0xFFFA: "MDCR", 0xFFFB: "SBYCR",
        0xFFFC: "P1CR", 0xFFFE: "P9DDR", 0xFFFF: "P9DR"}
for n, base in ((1, 0xFF90), (2, 0xFFA0), (3, 0xFFB0)):
    for off, name in ((0, "TCR"), (1, "TCSR"), (2, "FRC"), (4, "OCRA"),
                      (6, "OCRB"), (8, "ICR")):
        REGS[base + off] = "FRT%d_%s" % (n, name)
for n, base in ((1, 0xFFC0), (2, 0xFFC4), (3, 0xFFC8)):
    for off, name in ((0, "TCR"), (1, "DTR"), (2, "TCNT")):
        REGS[base + off] = "PWM%d_%s" % (n, name)

# vector number -> name; maximum mode, 4 bytes each at 4 * n
VECTORS = {0: "reset", 2: "invalid_insn", 3: "zero_divide", 4: "trap_vs",
           8: "address_error", 9: "trace", 11: "nmi", 32: "irq0", 33: "irq1",
           48: "tmr_cmia", 49: "tmr_cmib", 50: "tmr_ovi",
           52: "sci_eri", 53: "sci_rxi", 54: "sci_txi", 56: "adi"}
VECTORS.update({16 + i: "trapa%d" % i for i in range(16)})
for n, first in ((1, 36), (2, 40), (3, 44)):
    for k, src in enumerate(("ici", "ocia", "ocib", "fovi")):
        VECTORS[first + k] = "frt%d_%s" % (n, src)


def main():
    langdir = sys.argv[1]
    src = open(os.path.join(langdir, "h8539f.pspec")).read()
    # no default memory blocks: the R40 runs with on-chip RAM disabled and
    # executes ROM at 0xFB80-0xFDFF; import_r40.py lays out memory.
    # Reuse the module's TP:SP segment operator unchanged.
    a = src.index('<segmentop space=')
    seg = src[a:src.index("</segmentop>", a) + len("</segmentop>")]
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           "<!-- H8/532 mode 3 (maximum mode) for h8539f.sla; generated by",
           "     moppe tools/ghidra-r40/gen_pspec.py.  Vectors are 4 bytes:",
           "     byte 1 = CP, bytes 2-3 = PC. -->",
           "<processor_spec>",
           ' <programcounter register="PC"/>',
           ' <data_space space="ram" />',
           " " + seg,
           " <default_symbols>"]
    for n, name in sorted(VECTORS.items()):
        out.append('   <symbol name="vec_%s" address="ram:0x%08X" type="code_ptr"/>'
                   % (name, n * 4))
    for addr, name in sorted(REGS.items()):
        out.append('   <symbol name="%s" address="ram:0x%04X"/>' % (name, addr))
    out += [" </default_symbols>", "</processor_spec>", ""]
    with open(os.path.join(langdir, "h8532.pspec"), "w") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main()
