#!/usr/bin/env python3
"""
C -> firmware symbol glue (notes/toolchain.md).

    cglue.py build/*.rel > build/cglue.inc

SDCC prefixes C names with '_'.  For every '_x' the C objects reference but
do not define, emit '_x = x' so C can use the firmware's own variables and
routines under their assembler names.  Names starting with '__' are SDCC
runtime helpers and come from the SDCC library instead.
"""
import sys

from fwlink import read_rel


def main():
    refs, defs = set(), set()
    for path in sys.argv[1:]:
        rel = read_rel(path)
        refs |= rel.refs
        defs |= set(rel.defs)
    print("; generated by tools/r58/cglue.py from %s" % " ".join(sys.argv[1:]))
    for name in sorted(refs - defs):
        if name.startswith("_") and not name.startswith("__"):
            print("%s = %s" % (name, name[1:]))


if __name__ == "__main__":
    main()
