/* Writes floattest.c: random IEEE single operands and the host's results
   for + - * / compare and the conversions, as bit patterns; the generated
   program recomputes them with lcc-compiled float code on h8run and
   prints each mismatch.  Denormal operands and results are left out
   (float.c flushes them to zero).
       cc -O -o floatgen floatgen.c && ./floatgen [n] [seed] > floattest.c */
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static uint32_t bits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }
static float flt(uint32_t u) { float f; memcpy(&f, &u, 4); return f; }
static int ok(float f) { return isinf(f) || f == 0 || fpclassify(f) == FP_NORMAL; }

static uint32_t rnd(void)
{
	uint32_t u = (uint32_t)rand() << 17 ^ (uint32_t)rand() << 3 ^ rand();
	switch (rand() % 4) {
	case 0: return u;					/* anything */
	case 1: return (u & 0x807FFFFF) | (uint32_t)(120 + rand() % 16) << 23;	/* near 1 */
	case 2: return (u & 0x80000000) | (uint32_t)(rand() % 20 + 118) << 23;	/* powers of 2 */
	default: return bits((float)(int)(u % 2001) - 1000);	/* small integers */
	}
}

int main(int argc, char **argv)
{
	int n = argc > 1 ? atoi(argv[1]) : 200, i, k;
	srand(argc > 2 ? atoi(argv[2]) : 1);
	printf("/* generated by floatgen.c */\n#include <stdio.h>\n"
	       "static unsigned long v[][8] = {\n");
	for (i = 0; i < n; ) {
		uint32_t a = rnd(), b = rnd();
		float x = flt(a), y = flt(b);
		volatile float s = x + y, d = x - y, p = x * y, q = x / y;
		if (isnan(x) || isnan(y) || !ok(x) || !ok(y) || isinf(x) || isinf(y))
			continue;
		if (!ok(s) || !ok(d) || !ok(p) || (y != 0 && !ok(q)) || isnan(q))
			continue;
		/* (long)x out of range saturates in float.c */
		long c = fabsf(x) < 2147483648.0f ? (long)x : x < 0 ? -2147483647L - 1 : 2147483647L;
		printf("{0x%08XUL,0x%08XUL,0x%08XUL,0x%08XUL,0x%08XUL,0x%08XUL,%d,0x%08XUL},\n",
		       a, b, bits(s), bits(d), bits(p), y == 0 ? 0 : bits(q),
		       (x < y) - (x > y), (uint32_t)c);
		i++;
	}
	printf("};\nstatic long iv[][4] = {\n");
	for (k = 0; k < n; k++) {
		long l = k < 20 ? (long[]){0, 1, -1, 2, 32767, -32768, 65535, 2147483647L,
			-2147483647L - 1, 16777217, 16777219, -16777219, 33554435, 100, -100,
			7, 8388607, 8388608, 123456789, -987654321}[k]
			: (int32_t)((uint32_t)rand() << 17 ^ rand()) >> (rand() % 31);
		printf("{%ldL,0x%08XUL,0x%08XUL,0x%08XUL},\n", l, bits((float)l), bits((float)(uint32_t)l),
		       l >= 0 ? (uint32_t)(float)l : 0);
	}
	fputs("};\n"
"union fu { float f; unsigned long u; };\n"
"static float F(unsigned long u) { union fu x; x.u = u; return x.f; }\n"
"static unsigned long U(float f) { union fu x; x.u = 0; x.f = f; return x.u & 0xFFFFFFFFUL; }\n"
"static int bad;\n"
"static void chk(char *what, int i, unsigned long got, unsigned long want)\n"
"{ if (got != want) { printf(\"%s %d: %lx want %lx\\n\", what, i, got, want); bad++; } }\n"
"int main(void)\n{\n\tint i, n = sizeof v / sizeof v[0];\n"
"\tfor (i = 0; i < n; i++) {\n"
"\t\tfloat x = F(v[i][0]), y = F(v[i][1]);\n"
"\t\tchk(\"add\", i, U(x + y), v[i][2]);\n"
"\t\tchk(\"sub\", i, U(x - y), v[i][3]);\n"
"\t\tchk(\"mul\", i, U(x * y), v[i][4]);\n"
"\t\tif (v[i][5]) chk(\"div\", i, U(x / y), v[i][5]);\n"
"\t\tchk(\"cmp\", i, (x < y) - (x > y), (int)v[i][6]);\n"
"\t\tchk(\"le\", i, (x <= y) + 2 * (x == y) + 4 * (x != y) + 8 * (x >= y), \n"
"\t\t\t(int)v[i][6] == 1 ? 5 : (int)v[i][6] == 0 ? 11 : 12);\n"
"\t\tchk(\"cvfi\", i, (long)x & 0xFFFFFFFFUL, v[i][7]);\n"
"\t}\n"
"\tfor (i = 0; i < sizeof iv / sizeof iv[0]; i++) {\n"
"\t\tchk(\"cvif\", i, U((float)iv[i][0]), iv[i][1]);\n"
"\t\tchk(\"cvif2\", i, U((float)(int)iv[i][0]), U((float)(long)(int)iv[i][0]));\n"
"\t\tchk(\"cvuf\", i, U((float)(unsigned long)iv[i][0]), iv[i][2]);\n"
"\t\tchk(\"cvuf2\", i, U((float)(unsigned)iv[i][0]), U((float)(long)(unsigned)iv[i][0]));\n"
"\t\tif (iv[i][0] >= 0) chk(\"cvfu\", i, (unsigned long)F(iv[i][1]), iv[i][3]);\n"
"\t\tif (iv[i][0] >= -32768L && iv[i][0] <= 32767) chk(\"cvfi2\", i, (int)F(iv[i][1]), (int)iv[i][0]);\n"
"\t\tif (iv[i][0] >= 0 && iv[i][0] <= 65535L) chk(\"cvfu2\", i, (unsigned)F(iv[i][1]), (unsigned)iv[i][0]);\n"
"\t}\n"
"\tprintf(\"%d mismatches\\n\", bad);\n\treturn 0;\n}\n", stdout);
	return 0;
}
