#!/usr/bin/env python3
"""
C -> firmware symbol glue (notes/toolchain.md).

    cglue.py build-c/*.rel > build-c/cglue.inc

SDCC prefixes C names with '_'.  For every '_x' the C objects reference but
do not define, emit '_x = x' so C can use the firmware's own variables and
routines under their assembler names.  Names starting with '__' are SDCC
runtime helpers and come from the SDCC library instead.
"""
import re
import sys


def main():
    refs, defs = set(), set()
    for path in sys.argv[1:]:
        for line in open(path, errors="replace"):
            m = re.match(r"S (\S+) (Ref|Def)", line)
            if m:
                (refs if m.group(2) == "Ref" else defs).add(m.group(1))
    print("; generated by tools/cglue.py from %s" % " ".join(sys.argv[1:]))
    for name in sorted(refs - defs):
        if name.startswith("_") and not name.startswith("__"):
            print("%s = %s" % (name, name[1:]))


if __name__ == "__main__":
    main()
